### ISSUE TITLE
twdeps: undefined method `tasks' for nil:NilClass

### ISSUE THREAD

**Issue by lordcirth** [nerab/twdeps#27]
Trying out twdeps on Ubuntu 18.04, with taskwarrior 2.5.1 from Ubuntu repos, and twdeps 1.0.1 from 'gem install twdeps'.  Also installed 'bundler' as another issue recommended.

```
nfish@rsg-pc247:~$ task proj:Work.JH export | twdeps > ~/JH-`date -I`.png
[DEPRECATION] This gem has been renamed to optimist and will no longer be supported. Please switch to optimist as soon as possible.
twdeps: undefined method `tasks' for nil:NilClass
```
And the output file is empty.

**Comment by nerab** [comment]
Thanks for the report. Fixed with 0dc01e157cda736e2754a89a1e16f909b003179b and released as [v1.0.1](https://rubygems.org/gems/twdeps/versions/1.0.2).

**Comment by lordcirth** [comment]
Thanks for the quick response!  Did you mean 1.0.2? That's where the link goes.
I tried updating to 1.0.2 using gem, but I still get the same error.  I'm not familiar with gem, perhaps I updated it wrong?  I uninstalled 1.0.1 since I noticed gem had left it around...

**Comment by nerab** [comment]
Indeed, I meant to say 1.0.2. I will check what's up as part of #28
